// import test from './debugLogic/diff.js'
// import test from './debugLogic/basic.js'
// import test from './debugLogic/lifecycle.js'
// import test from './debugLogic/mylifecycle.js'
// import test from './debugLogic/derivedState.js'
// import test from './debugLogic/getSnapshotBeforeUpdate.js'
// import test from './debugLogic/pureComp  onent.js'
// import test from './debugLogic/counter.js'
// import test from './debugLogic/chatServerUseEffect.js'
import test from './debugLogic/ref.js'
test()